/**
 * Alter Powers (indices 30-37)
 *
 * Powers that modify game mechanics: blocking actions, changing initiative order,
 * and protecting players from effects.
 */

import type { InfiltrationPower } from "./types";

export const ALTER_POWERS: InfiltrationPower[] = [
  /** [30] Nope! - Block # Player From Doing Actions | Item: Block, Where: Player, Min: 1, Max: 5, FixedInit, AllowRandom, Complexity: 2 */
  {
    index: 30,
    initiative: "4",
    powerName: "Nope!",
    description: "Block # Player From Doing Actions",
    type: "Alter",
    item: "Block",
    where: "Player",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: true,
    vault: false,
    complexity: 2,
  },
  /** [31] Role Jam - Block # Role From Doing Actions | Item: Block, Where: Role, Min: 1, Max: 5, FixedInit, Complexity: 3 */
  {
    index: 31,
    initiative: "4",
    powerName: "Role Jam",
    description: "Block # Role From Doing Actions",
    type: "Alter",
    item: "Block",
    where: "Role",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  /** [32] Priority Warp - Alter # Players Action * Priority | Item: Initiative, Where: Player, Min: 1, Max: 5, FixedInit, AllowRandom, Complexity: 3 */
  {
    index: 32,
    initiative: "2",
    powerName: "Priority Warp",
    description: "Alter # Players Action * Priority",
    type: "Alter",
    item: "Initiative",
    where: "Player",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: true,
    vault: false,
    complexity: 3,
  },
  /** [33] Order Rewrite - Alter # Roles Action * Priority | Item: Initiative, Where: Role, Min: 1, Max: 5, FixedInit, Complexity: 3 */
  {
    index: 33,
    initiative: "2",
    powerName: "Order Rewrite",
    description: "Alter # Roles Action * Priority",
    type: "Alter",
    item: "Initiative",
    where: "Role",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  /** [34] Hard Priority - Set # Players Action Priority | Item: Initiative, Where: Player, Min: 1, Max: 5, AllowRandom, Complexity: 3 */
  {
    index: 34,
    initiative: "1",
    powerName: "Hard Priority",
    description: "Set # Players Action Priority",
    type: "Alter",
    item: "Initiative",
    where: "Player",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: false,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: true,
    vault: false,
    complexity: 3,
  },
  /** [35] Order Rule - Set # Roles Action Priority | Item: Initiative, Where: Role, Min: 1, Max: 5, Complexity: 3 */
  {
    index: 35,
    initiative: "1",
    powerName: "Order Rule",
    description: "Set # Roles Action Priority",
    type: "Alter",
    item: "Initiative",
    where: "Role",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: false,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  /** [36] Shield - Protect # Player From * Actions | Item: Protect, Where: Player, Min: 1, Max: 5, FixedInit, AllowRandom, Complexity: 2 */
  {
    index: 36,
    initiative: "3",
    powerName: "Shield",
    description: "Protect # Player From * Actions",
    type: "Alter",
    item: "Protect",
    where: "Player",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: true,
    vault: false,
    complexity: 2,
  },
  /** [37] Guard - Protect # * Roles From * Actions | Item: Protect, Where: Role, Min: 1, Max: 5, FixedInit, Complexity: 3 */
  {
    index: 37,
    initiative: "3",
    powerName: "Guard",
    description: "Protect # * Roles From * Actions",
    type: "Alter",
    item: "Protect",
    where: "Role",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
];
