/**
 * Alter Powers (indices 30-37)
 *
 * Powers that modify game mechanics: blocking actions, changing initiative order,
 * and protecting players from effects.
 */

import type { InfiltrationPower } from "./types";

export const ALTER_POWERS: InfiltrationPower[] = [
  {
    index: 30,
    initiative: "4",
    powerName: "Nope!",
    description: "Block # Player From Doing Actions",
    type: "Alter",
    item: "Block",
    where: "Player",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: false,
    complexity: 2,
  },
  {
    index: 31,
    initiative: "4",
    powerName: "Role Jam",
    description: "Block # Role From Doing Actions",
    type: "Alter",
    item: "Block",
    where: "Role",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 32,
    initiative: "2",
    powerName: "Priority Warp",
    description: "Alter # Players Action * Priority",
    type: "Alter",
    item: "Initiative",
    where: "Player",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: false,
    complexity: 3,
  },
  {
    index: 33,
    initiative: "2",
    powerName: "Order Rewrite",
    description: "Alter # Roles Action * Priority",
    type: "Alter",
    item: "Initiative",
    where: "Role",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 34,
    initiative: "1",
    powerName: "Hard Priority",
    description: "Set # Players Action Priority",
    type: "Alter",
    item: "Initiative",
    where: "Player",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: false,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: false,
    complexity: 3,
  },
  {
    index: 35,
    initiative: "1",
    powerName: "Order Rule",
    description: "Set # Roles Action Priority",
    type: "Alter",
    item: "Initiative",
    where: "Role",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: false,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 36,
    initiative: "3",
    powerName: "Shield",
    description: "Protect # Player From * Actions",
    type: "Alter",
    item: "Protect",
    where: "Player",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: false,
    complexity: 2,
  },
  {
    index: 37,
    initiative: "3",
    powerName: "Guard",
    description: "Protect # * Roles From * Actions",
    type: "Alter",
    item: "Protect",
    where: "Role",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
];
