/**
 * Learn Powers (indices 1, 3-4, 6-13, 16)
 *
 * Powers that allow players to discover information about other players,
 * NPCs, or game state. These are generally low-complexity information-gathering abilities.
 * Powers with targetScopes can target Players, NPCs, or both (selected during character creation).
 */

import type { InfiltrationPower } from "./types";

export const LEARN_POWERS: InfiltrationPower[] = [
  /** [1] Role Peek - Learn # Roles | Item: Role, Where: Player, Min: 1, Max: 3, Infected, Complexity: 2, TargetScopes: Players/NPC/Both */
  {
    index: 1,
    initiative: "10 90",
    powerName: "Role Peek",
    description: "Learn # Roles",
    type: "Learn",
    item: "Role",
    where: "Player",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
    targetScopes: ["Players Only", "NPC Only", "Players and NPC"],
  },
  /** [3] Last Look - Learn Own Role at the End | Item: Role, Where: Self, Qty: 1, FixedAction, FixedInit, Complexity: 1 */
  {
    index: 3,
    initiative: "10 90",
    powerName: "Last Look",
    description: "Learn Own Role at the End",
    type: "Learn",
    item: "Role",
    where: "Self",
    min: 1,
    max: 1,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 1,
  },
  /** [4] Allegiance Check - Learn # Teams | Item: Team, Where: Player, Min: 1, Max: 3, Infected, Complexity: 2, TargetScopes: Players/NPC/Both */
  {
    index: 4,
    initiative: "10 90",
    powerName: "Allegiance Check",
    description: "Learn # Teams",
    type: "Learn",
    item: "Team",
    where: "Player",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
    targetScopes: ["Players Only", "NPC Only", "Players and NPC"],
  },
  /** [6] Roll Rolecall - Learn # Players With Role | Item: Players, Where: Role, Min: 1, Max: 99, Complexity: 3 */
  {
    index: 6,
    initiative: "10 90",
    powerName: "Roll Rolecall",
    description: "Learn # Players With Role",
    type: "Learn",
    item: "Players",
    where: "Role",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: false,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  /** [7] Role Beacon - Learn All Players With Same Role | Item: Players, Where: Same Role, Qty: 99, FixedAction, FixedInit, Complexity: 3 */
  {
    index: 7,
    initiative: "10",
    powerName: "Role Beacon",
    description: "Learn All Players With Same Role",
    type: "Learn",
    item: "Players",
    where: "Same Role",
    min: 99,
    max: 99,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  /** [8] Team Echo - Learn # Players With Same Team | Item: Players, Where: Same Team, Min: 1, Max: 5, FixedAction, Infected, Complexity: 3 */
  {
    index: 8,
    initiative: "10 90",
    powerName: "Team Echo",
    description: "Learn # Players With Same Team",
    type: "Learn",
    item: "Players",
    where: "Same Team",
    min: 1,
    max: 5,
    fixedAction: true,
    fixedInitiative: false,
    infected: true,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  /** [9] Action Trace - Learn # Players Did Action Type | Item: Players, Where: Type, Min: 1, Max: 99, FixedInit, Infected, Complexity: 3 */
  {
    index: 9,
    initiative: "90",
    powerName: "Action Trace",
    description: "Learn # Players Did Action Type",
    type: "Learn",
    item: "Players",
    where: "Type",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: true,
    infected: true,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  /** [10] Action Log - Learn # Players Who Moved/Learned | Item: Players, Where: Action, Min: 1, Max: 99, FixedInit, Infected, Complexity: 3 */
  {
    index: 10,
    initiative: "90",
    powerName: "Action Log",
    description: "Learn # Players Who Moved/Learned",
    type: "Learn",
    item: "Players",
    where: "Action",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: true,
    infected: true,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  /** [11] Tactic Tell - Learn # Player Action Type | Item: Type, Where: Player, Min: 1, Max: 3, Infected, Complexity: 3 */
  {
    index: 11,
    initiative: "10 90",
    powerName: "Tactic Tell",
    description: "Learn # Player Action Type",
    type: "Learn",
    item: "Type",
    where: "Player",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  /** [12] Role Tally - Learn up to # of a Role | Item: Amount, Where: Role, Min: 1, Max: 99, Infected, Complexity: 2, TargetScopes: Players/NPC/Both */
  {
    index: 12,
    initiative: "10 90",
    powerName: "Role Tally",
    description: "Learn up to # of a Role",
    type: "Learn",
    item: "Amount",
    where: "Role",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
    targetScopes: ["Players Only", "NPC Only", "Players and NPC"],
  },
  /** [13] Team Tally - Learn up to # of a Team | Item: Amount, Where: Association, Min: 1, Max: 3, Infected, Complexity: 2, TargetScopes: Players/NPC/Both */
  {
    index: 13,
    initiative: "10 90",
    powerName: "Team Tally",
    description: "Learn up to # of a Team",
    type: "Learn",
    item: "Amount",
    where: "Association",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
    targetScopes: ["Players Only", "NPC Only", "Players and NPC"],
  },
  /** [16] Sixth Sense - Learn if # Players Were Moved | Item: Status, Where: Player, Min: 1, Max: 99, Infected, Complexity: 2 */
  {
    index: 16,
    initiative: "90",
    powerName: "Sixth Sense",
    description: "Learn if # Players Were Moved",
    type: "Learn",
    item: "Status",
    where: "Player",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
];
