/**
 * Learn Powers (indices 1-16)
 *
 * Powers that allow players to discover information about other players,
 * the center, or game state. These are generally low-complexity information-gathering abilities.
 */

import type { InfiltrationPower } from "./types";

export const LEARN_POWERS: InfiltrationPower[] = [
  {
    index: 1,
    initiative: "10 90",
    powerName: "Role Peek",
    description: "Learn # Player's Roles",
    type: "Learn",
    item: "Role",
    where: "Player",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: true,
    lookPostAction: false,
    doPower: false,
    selfDestruct: true,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 2,
    initiative: "10 90",
    powerName: "Vault Peek",
    description: "Learn # Center's Roles",
    type: "Learn",
    item: "Role",
    where: "Center",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: true,
    lookPostAction: false,
    doPower: false,
    selfDestruct: true,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 3,
    initiative: "10 90",
    powerName: "Last Look",
    description: "Learn Own Role at the End",
    type: "Learn",
    item: "Role",
    where: "Self",
    min: 1,
    max: 1,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: true,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 1,
  },
  {
    index: 4,
    initiative: "10 90",
    powerName: "Allegiance Check",
    description: "Learn # Player's Teams",
    type: "Learn",
    item: "Team",
    where: "Player",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: true,
    lookPostAction: false,
    doPower: false,
    selfDestruct: true,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 5,
    initiative: "10 90",
    powerName: "Vault Allegiance",
    description: "Learn # Center's Teams",
    type: "Learn",
    item: "Team",
    where: "Center",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: true,
    lookPostAction: false,
    doPower: false,
    selfDestruct: true,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 6,
    initiative: "10 90",
    powerName: "Roll Rolecall",
    description: "Learn # Players With Role",
    type: "Learn",
    item: "Players",
    where: "Role",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: false,
    infected: false,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 7,
    initiative: "10",
    powerName: "Role Beacon",
    description: "Learn All Players With Same Role",
    type: "Learn",
    item: "Players",
    where: "Same Role",
    min: 99,
    max: 99,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 8,
    initiative: "10 90",
    powerName: "Team Echo",
    description: "Learn # Players With Same Team",
    type: "Learn",
    item: "Players",
    where: "Same Team",
    min: 1,
    max: 5,
    fixedAction: true,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 9,
    initiative: "90",
    powerName: "Action Trace",
    description: "Learn # Players Did Action Type",
    type: "Learn",
    item: "Players",
    where: "Type",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: true,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 10,
    initiative: "90",
    powerName: "Action Log",
    description: "Learn # Players Who Moved/Learned",
    type: "Learn",
    item: "Players",
    where: "Action",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: true,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 11,
    initiative: "10 90",
    powerName: "Tactic Tell",
    description: "Learn # Player Action Type",
    type: "Learn",
    item: "Type",
    where: "Player",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 12,
    initiative: "10 90",
    powerName: "Role Tally",
    description: "Learn up to # role are Players",
    type: "Learn",
    item: "Amount",
    where: "Role",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 13,
    initiative: "10 90",
    powerName: "Team Tally",
    description: "Learn up to # Team are Players",
    type: "Learn",
    item: "Amount",
    where: "Association",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 14,
    initiative: "10 90",
    powerName: "Who's Missing",
    description: "Learn up to # role are Center",
    type: "Learn",
    item: "Amount",
    where: "Role",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 15,
    initiative: "10 90",
    powerName: "Absentee Ballot",
    description: "Learn up to # Team are Center",
    type: "Learn",
    item: "Amount",
    where: "Association",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 16,
    initiative: "90",
    powerName: "Sixth Sense",
    description: "Learn if # Players Were Moved",
    type: "Learn",
    item: "Status",
    where: "Player",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
];
