/**
 * Reveal Powers (indices 17-20)
 *
 * Powers that publicly reveal role information to all players.
 * These are higher-stakes powers that expose information to the whole game.
 */

import type { InfiltrationPower } from "./types";

export const REVEAL_POWERS: InfiltrationPower[] = [
  {
    index: 17,
    initiative: "5 95",
    powerName: "Expose Role",
    description: "Reveal # Player Role",
    type: "Reveal",
    item: "Role",
    where: "Player",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: false,
    complexity: 3,
  },
  {
    index: 18,
    initiative: "5 95",
    powerName: "Open Vault",
    description: "Reveal # Center Role",
    type: "Reveal",
    item: "Role",
    where: "Center",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: false,
    complexity: 3,
  },
  {
    index: 19,
    initiative: "5 95",
    powerName: "Face Reveal",
    description: "Reveal self",
    type: "Reveal",
    item: "Role",
    where: "Self",
    min: 1,
    max: 1,
    fixedAction: true,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 1,
  },
  {
    index: 20,
    initiative: "5 95",
    powerName: "Role Spotlight",
    description: "Reveal # player of role",
    type: "Reveal",
    item: "Role",
    where: "Role",
    min: 1,
    max: 5,
    fixedAction: true,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
];
