/**
 * Swap Powers (indices 21-27)
 *
 * Powers that swap roles and team assignments between players.
 * These are complex powers that dramatically shift the game state.
 */

import type { InfiltrationPower } from "./types";

export const SWAP_POWERS: InfiltrationPower[] = [
  /** [21] Role Swap - Swap Two Players Roles | Item: Role, Where: Player, Qty: 2, FixedInit, AllowRandom, Vault, Complexity: 2 */
  {
    index: 21,
    initiative: "50",
    powerName: "Role Swap",
    description: "Swap Two Players Roles",
    type: "Swap",
    item: "Role",
    where: "Player",
    min: 2,
    max: 2,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: true,
    vault: true,
    vaultName: "Vault Swap",
    complexity: 2,
  },
  /** [22] Self Swap - Swap One Players Role With Own Role | Item: Role, Where: Player, Qty: 1, FixedInit, LookPostAction, DoPower, AllowRandom, Vault, Complexity: 2 */
  {
    index: 22,
    initiative: "50",
    powerName: "Self Swap",
    description: "Swap One Players Role With Own Role",
    type: "Swap",
    item: "Role",
    where: "Player",
    min: 1,
    max: 1,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    lookPostAction: true,
    doPower: true,
    allowRandom: true,
    vault: true,
    vaultName: "Vault Trade-In",
    complexity: 2,
  },
  /** [23] Swap Role Team - Swap A Player's Role and Team | Item: Role Team, Where: Player, Qty: 2, FixedInit, AllowRandom, Vault, Complexity: 2 */
  {
    index: 23,
    initiative: "50",
    powerName: "Swap Role Team",
    description: "Swap A Player's Role and Team",
    type: "Swap",
    item: "Role Team",
    where: "Player",
    min: 2,
    max: 2,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: true,
    vault: true,
    vaultName: "Vault Trade-Out",
    complexity: 2,
  },
  /** [24] Swap Reversal - Swap # Swaps of Roles | Item: Role, Where: Reversal, Min: 1, Max: 5, FixedAction, FixedInit, Complexity: 3 */
  {
    index: 24,
    initiative: "60",
    powerName: "Swap Reversal",
    description: "Swap # Swaps of Roles",
    type: "Swap",
    item: "Role",
    where: "Reversal",
    min: 1,
    max: 5,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    vaultName: "Vault Reversal",
    complexity: 3,
  },
  /** [25] Team Exchange - Swap Own Team With Another Player | Item: Team, Where: Self, Qty: 1, FixedInit, LookPostAction, DoPower, AllowRandom, Vault, Complexity: 2 */
  {
    index: 25,
    initiative: "50",
    powerName: "Team Exchange",
    description: "Swap Own Team With Another Player",
    type: "Swap",
    item: "Team",
    where: "Self",
    min: 1,
    max: 1,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    lookPostAction: true,
    doPower: true,
    allowRandom: true,
    vault: true,
    vaultName: "Vault Exchange",
    complexity: 2,
  },
  /** [26] Recruit - Swap another's Team to your own | Item: Team, Where: Self, Qty: 1, FixedInit, AllowRandom, Vault, Complexity: 3 */
  {
    index: 26,
    initiative: "50",
    powerName: "Recruit",
    description: "Swap another's Team to your own",
    type: "Swap",
    item: "Team",
    where: "Self",
    min: 1,
    max: 1,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: true,
    vault: true,
    vaultName: "Vault Recruit",
    complexity: 3,
  },
  /** [27] Team Shuffle - Swap Two Players Teams | Item: Team, Where: Player Player, Qty: 2, FixedInit, AllowRandom, Vault, Complexity: 2 */
  {
    index: 27,
    initiative: "50",
    powerName: "Team Shuffle",
    description: "Swap Two Players Teams",
    type: "Swap",
    item: "Team",
    where: "Player Player",
    min: 2,
    max: 2,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: true,
    vault: true,
    vaultName: "Vault Shuffle",
    complexity: 2,
  },
];
