/**
 * Tamper Powers (indices 38-44)
 *
 * Powers that interfere with voting and player submissions.
 * These are high-impact powers that directly affect the voting phase.
 */

import type { InfiltrationPower } from "./types";

export const TAMPER_POWERS: InfiltrationPower[] = [
  {
    index: 38,
    initiative: "0",
    powerName: "Mute Vote",
    description: "Silence # Player From Voting",
    type: "Tamper",
    item: "Silence",
    where: "Player",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: true,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: false,
    complexity: 2,
  },
  {
    index: 39,
    initiative: "0",
    powerName: "Vote Jam",
    description: "Silence # Role From Voting",
    type: "Tamper",
    item: "Silence",
    where: "Role",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: true,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 40,
    initiative: "0",
    powerName: "Vote Encore",
    description: "Duplicate Own Vote",
    type: "Tamper",
    item: "Duplicate",
    where: "Player",
    min: 0,
    max: 0,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 1,
  },
  {
    index: 41,
    initiative: "0",
    powerName: "Vote Echo",
    description: "Duplicate Role Votes",
    type: "Tamper",
    item: "Duplicate",
    where: "Role",
    min: 0,
    max: 0,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 42,
    initiative: "0",
    powerName: "Double Tap",
    description: "Duplicate Own Vote",
    type: "Tamper",
    item: "Duplicate",
    where: "Self",
    min: 0,
    max: 0,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 1,
  },
  {
    index: 43,
    initiative: "0",
    powerName: "Death Vote",
    description: "Players Vote Is Killed",
    type: "Tamper",
    item: "Kill",
    where: "Player",
    min: 1,
    max: 1,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 44,
    initiative: "0",
    powerName: "Last Laugh",
    description: "Players Vote Is Killed, If Player is Killed",
    type: "Tamper",
    item: "Destruct",
    where: "Player",
    min: 1,
    max: 1,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
];
