/**
 * Tamper Powers (indices 38-44)
 *
 * Powers that interfere with voting and player votes.
 * These are high-impact powers that directly affect the voting phase.
 */

import type { InfiltrationPower } from "./types";

export const TAMPER_POWERS: InfiltrationPower[] = [
  /** [38] Mute Vote - Silence # Player From Voting | Item: Silence, Where: Player, Min: 1, Max: 5, FixedInit, AllowRandom, Complexity: 2 */
  {
    index: 38,
    initiative: "0",
    powerName: "Mute Vote",
    description: "Silence # Player From Voting",
    type: "Tamper",
    item: "Silence",
    where: "Player",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: true,
    vault: false,
    complexity: 2,
  },
  /** [39] Vote Jam - Silence # Role From Voting | Item: Silence, Where: Role, Min: 1, Max: 5, FixedInit, Complexity: 3 */
  {
    index: 39,
    initiative: "0",
    powerName: "Vote Jam",
    description: "Silence # Role From Voting",
    type: "Tamper",
    item: "Silence",
    where: "Role",
    min: 1,
    max: 5,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  /** [40] Vote Encore - Duplicate Own Vote | Item: Duplicate, Where: Player, FixedAction, FixedInit, Complexity: 1 */
  {
    index: 40,
    initiative: "0",
    powerName: "Vote Encore",
    description: "Duplicate Own Vote",
    type: "Tamper",
    item: "Duplicate",
    where: "Player",
    min: 0,
    max: 0,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 1,
  },
  /** [41] Vote Echo - Duplicate Role Votes | Item: Duplicate, Where: Role, FixedAction, FixedInit, Complexity: 3 */
  {
    index: 41,
    initiative: "0",
    powerName: "Vote Echo",
    description: "Duplicate Role Votes",
    type: "Tamper",
    item: "Duplicate",
    where: "Role",
    min: 0,
    max: 0,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  /** [42] Double Tap - Duplicate Own Vote | Item: Duplicate, Where: Self, FixedAction, FixedInit, Complexity: 1 */
  {
    index: 42,
    initiative: "0",
    powerName: "Double Tap",
    description: "Duplicate Own Vote",
    type: "Tamper",
    item: "Duplicate",
    where: "Self",
    min: 0,
    max: 0,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 1,
  },
  /** [43] Death Vote - Players Vote Is Killed | Item: Kill, Where: Player, Qty: 1, FixedAction, FixedInit, Complexity: 2 */
  {
    index: 43,
    initiative: "0",
    powerName: "Death Vote",
    description: "Players Vote Is Killed",
    type: "Tamper",
    item: "Kill",
    where: "Player",
    min: 1,
    max: 1,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  /** [44] Last Laugh - Players Vote Is Killed, If Player is Killed | Item: Destruct, Where: Player, Qty: 1, FixedAction, FixedInit, Complexity: 2 */
  {
    index: 44,
    initiative: "0",
    powerName: "Last Laugh",
    description: "Players Vote Is Killed, If Player is Killed",
    type: "Tamper",
    item: "Destruct",
    where: "Player",
    min: 1,
    max: 1,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    lookPostAction: false,
    doPower: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
];
