/**
 * Infiltration Powers Data
 * Parsed from /data/infiltration_powers.csv
 */

export type InfiltrationPower = {
  index: number;
  initiative: string;
  powerName: string;
  description: string;
  type: string;
  item: string;
  where: string;
  min: number;
  max: number;
  fixedAction: boolean;
  fixedInitiative: boolean;
  infected: boolean;
  suicidal: boolean;
  murderer: boolean;
  predicter: boolean;
  silencer: boolean;
  twoXVote: boolean;
  lookPostAction: boolean;
  doPower: boolean;
  selfDestruct: boolean;
  allowRandom: boolean;
  vault: boolean;
  complexity: number;
};

export const INFILTRATION_POWERS: InfiltrationPower[] = [
  {
    index: 1,
    initiative: "10 90",
    powerName: "Role Peek",
    description: "Learn # Player''s Roles",
    type: "Learn",
    item: "Role",
    where: "Player",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: true,
    lookPostAction: false,
    doPower: false,
    selfDestruct: true,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 2,
    initiative: "10 90",
    powerName: "Vault Peek",
    description: "Learn # Center''s Roles",
    type: "Learn",
    item: "Role",
    where: "Center",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: true,
    lookPostAction: false,
    doPower: false,
    selfDestruct: true,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 3,
    initiative: "10 90",
    powerName: "Last Look",
    description: "Learn Final Role",
    type: "Learn",
    item: "Role",
    where: "Self",
    min: 1,
    max: 1,
    fixedAction: true,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: true,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 1,
  },
  {
    index: 4,
    initiative: "10 90",
    powerName: "Allegiance Check",
    description: "Learn # Player''s Teams",
    type: "Learn",
    item: "Team",
    where: "Player",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: true,
    lookPostAction: false,
    doPower: false,
    selfDestruct: true,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 5,
    initiative: "10 90",
    powerName: "Vault Allegiance",
    description: "Learn # Center''s Teams",
    type: "Learn",
    item: "Team",
    where: "Center",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: true,
    lookPostAction: false,
    doPower: false,
    selfDestruct: true,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 6,
    initiative: "10 90",
    powerName: "Roll Rolecall",
    description: "Learn # Players With Role",
    type: "Learn",
    item: "Players",
    where: "Role",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: false,
    infected: false,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 7,
    initiative: "10 90",
    powerName: "Role Beacon",
    description: "Learn All Players With Same Role",
    type: "Learn",
    item: "Players",
    where: "Role Assoc.",
    min: 99,
    max: 99,
    fixedAction: true,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 8,
    initiative: "10 90",
    powerName: "Team Echo",
    description: "Learn # Players With Same Team",
    type: "Learn",
    item: "Players",
    where: "Team Assoc.",
    min: 1,
    max: 99,
    fixedAction: true,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 9,
    initiative: "90",
    powerName: "Action Trace",
    description: "Learn # Players Did Action Type",
    type: "Learn",
    item: "Players",
    where: "Type",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: true,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 10,
    initiative: "90",
    powerName: "Action Log",
    description: "Learn # Players Who Moved/Learned",
    type: "Learn",
    item: "Players",
    where: "Action",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: true,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 11,
    initiative: "10 90",
    powerName: "Tactic Tell",
    description: "Learn # Player Action Type",
    type: "Learn",
    item: "Type",
    where: "Player",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 12,
    initiative: "10 90",
    powerName: "Role Tally",
    description: "Learn up to # role are Players",
    type: "Learn",
    item: "Amount",
    where: "Role",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 13,
    initiative: "10 90",
    powerName: "Team Tally",
    description: "Learn up to # Team are Players",
    type: "Learn",
    item: "Amount",
    where: "Association",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 14,
    initiative: "10 90",
    powerName: "Who''s Missing",
    description: "Learn up to # role are Center",
    type: "Learn",
    item: "Amount",
    where: "Role",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 15,
    initiative: "10 90",
    powerName: "Absentee Ballot",
    description: "Learn up to # Team are Center",
    type: "Learn",
    item: "Amount",
    where: "Association",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 16,
    initiative: "90",
    powerName: "Sixth Sense",
    description: "Learn if # Players Were Moved",
    type: "Learn",
    item: "Status",
    where: "Player",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 17,
    initiative: "5 95",
    powerName: "Expose Role",
    description: "Reveal # Player Role",
    type: "Reveal",
    item: "Role",
    where: "Player",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: false,
    complexity: 3,
  },
  {
    index: 18,
    initiative: "5 95",
    powerName: "Open Vault",
    description: "Reveal # Center Role",
    type: "Reveal",
    item: "Role",
    where: "Center",
    min: 1,
    max: 3,
    fixedAction: false,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: false,
    complexity: 3,
  },
  {
    index: 19,
    initiative: "5 95",
    powerName: "Face Reveal",
    description: "Reveal self",
    type: "Reveal",
    item: "Role",
    where: "Self",
    min: 1,
    max: 1,
    fixedAction: true,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 1,
  },
  {
    index: 20,
    initiative: "5 95",
    powerName: "Role Spotlight",
    description: "Reveal # player of role",
    type: "Reveal",
    item: "Role",
    where: "Role",
    min: 1,
    max: 99,
    fixedAction: true,
    fixedInitiative: false,
    infected: true,
    suicidal: true,
    murderer: true,
    predicter: true,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 21,
    initiative: "50",
    powerName: "Role Swap",
    description: "Swap Two Players Roles (can use Vault)",
    type: "Swap",
    item: "Role",
    where: "Player",
    min: 2,
    max: 2,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: true,
    complexity: 2,
  },
  {
    index: 22,
    initiative: "50",
    powerName: "Self Swap",
    description: "Swap One Players Role With Own Role (can use Vault)",
    type: "Swap",
    item: "Role",
    where: "Player",
    min: 1,
    max: 1,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: true,
    doPower: true,
    selfDestruct: false,
    allowRandom: true,
    vault: true,
    complexity: 2,
  },
  {
    index: 23,
    initiative: "50",
    powerName: "Swap Role Team",
    description: "Swap A Player''s Role and Team",
    type: "Swap",
    item: "Role Team",
    where: "Player",
    min: 2,
    max: 2,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: true,
    complexity: 2,
  },
  {
    index: 24,
    initiative: "60",
    powerName: "Swap Reversal",
    description: "Swap # Swaps of Roles",
    type: "Swap",
    item: "Role",
    where: "Role",
    min: 1,
    max: 99,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 25,
    initiative: "50",
    powerName: "Team Exchange",
    description: "Swap Own Team With Another Player",
    type: "Swap",
    item: "Team",
    where: "Self",
    min: 1,
    max: 1,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: true,
    doPower: true,
    selfDestruct: false,
    allowRandom: true,
    vault: true,
    complexity: 2,
  },
  {
    index: 26,
    initiative: "50",
    powerName: "Recruit",
    description: "Swap another''s Team to your own",
    type: "Swap",
    item: "Team",
    where: "Self",
    min: 1,
    max: 1,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: true,
    complexity: 3,
  },
  {
    index: 27,
    initiative: "50",
    powerName: "Team Shuffle",
    description: "Swap Two Players Teams",
    type: "Swap",
    item: "Team",
    where: "Player Player",
    min: 2,
    max: 2,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: true,
    complexity: 2,
  },
  {
    index: 28,
    initiative: "0",
    powerName: "Deathwish",
    description: "Wins If Voted Out",
    type: "Condition",
    item: "Win",
    where: "Self",
    min: 0,
    max: 0,
    fixedAction: false,
    fixedInitiative: true,
    infected: true,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 1,
  },
  {
    index: 29,
    initiative: "0",
    powerName: "Oracle",
    description: "Wins If Vote Is Infiltrator",
    type: "Condition",
    item: "Win",
    where: "Vote",
    min: 0,
    max: 0,
    fixedAction: false,
    fixedInitiative: true,
    infected: true,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 1,
  },
  {
    index: 30,
    initiative: "4",
    powerName: "Nope!",
    description: "Block # Player From Doing Actions",
    type: "Alter",
    item: "Block",
    where: "Player",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: false,
    complexity: 2,
  },
  {
    index: 31,
    initiative: "4",
    powerName: "Role Jam",
    description: "Block # Role From Doing Actions",
    type: "Alter",
    item: "Block",
    where: "Role",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 32,
    initiative: "2",
    powerName: "Priority Warp",
    description: "Alter # Players Action * Priority",
    type: "Alter",
    item: "Initiative",
    where: "Player",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: false,
    complexity: 3,
  },
  {
    index: 33,
    initiative: "2",
    powerName: "Order Rewrite",
    description: "Alter # Roles Action * Priority",
    type: "Alter",
    item: "Initiative",
    where: "Role",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 34,
    initiative: "1",
    powerName: "Hard Priority",
    description: "Set # Players Action Priority",
    type: "Alter",
    item: "Initiative",
    where: "Player",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: false,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: false,
    complexity: 3,
  },
  {
    index: 35,
    initiative: "1",
    powerName: "Order Rule",
    description: "Set # Roles Action Priority",
    type: "Alter",
    item: "Initiative",
    where: "Role",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: false,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 36,
    initiative: "3",
    powerName: "Shield",
    description: "Protect # Player From * Actions",
    type: "Alter",
    item: "Protect",
    where: "Player",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: false,
    complexity: 2,
  },
  {
    index: 37,
    initiative: "3",
    powerName: "Guard",
    description: "Protect # * Roles From * Actions",
    type: "Alter",
    item: "Protect",
    where: "Role",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 38,
    initiative: "0",
    powerName: "Mute Vote",
    description: "Silence # Player From Voting",
    type: "Tamper",
    item: "Silence",
    where: "Player",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: true,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: true,
    vault: false,
    complexity: 2,
  },
  {
    index: 39,
    initiative: "0",
    powerName: "Vote Jam",
    description: "Silence # Role From Voting",
    type: "Tamper",
    item: "Silence",
    where: "Role",
    min: 1,
    max: 99,
    fixedAction: false,
    fixedInitiative: true,
    infected: false,
    suicidal: true,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 40,
    initiative: "0",
    powerName: "Vote Encore",
    description: "Duplicate Own Vote",
    type: "Tamper",
    item: "Duplicate",
    where: "Player",
    min: 0,
    max: 0,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 1,
  },
  {
    index: 41,
    initiative: "0",
    powerName: "Vote Echo",
    description: "Duplicate Role Votes",
    type: "Tamper",
    item: "Duplicate",
    where: "Role",
    min: 0,
    max: 0,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 3,
  },
  {
    index: 42,
    initiative: "0",
    powerName: "Double Tap",
    description: "Duplicate Own Vote",
    type: "Tamper",
    item: "Duplicate",
    where: "Self",
    min: 0,
    max: 0,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 1,
  },
  {
    index: 43,
    initiative: "0",
    powerName: "Death Vote",
    description: "Players Vote Is Killed",
    type: "Tamper",
    item: "Kill",
    where: "Player",
    min: 1,
    max: 1,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 44,
    initiative: "0",
    powerName: "Last Laugh",
    description: "Players Vote Is Killed, If Player is Killed",
    type: "Tamper",
    item: "Destruct",
    where: "Player",
    min: 1,
    max: 1,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 45,
    initiative: "0",
    powerName: "Time Warp",
    description: "Shorten or lengthen discussion times",
    type: "Settings",
    item: "Time",
    where: "Room",
    min: 0,
    max: 99,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 2,
  },
  {
    index: 46,
    initiative: "0",
    powerName: "No Action",
    description: "Has no power, can be modified",
    type: "None",
    item: "NoAction",
    where: "None",
    min: 0,
    max: 0,
    fixedAction: true,
    fixedInitiative: true,
    infected: false,
    suicidal: false,
    murderer: false,
    predicter: false,
    silencer: false,
    twoXVote: false,
    lookPostAction: false,
    doPower: false,
    selfDestruct: false,
    allowRandom: false,
    vault: false,
    complexity: 1,
  },
];
